name: Deploy dev to cPanel

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Deploy to cPanel dev folder
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /
          timeout: 120000
          log-level: standard
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            config/database.local.php
            *.zip
